### ISSUE TITLE
[Bug] os-lib 0.10.7 breaks expecty macro in weaver

### ISSUE THREAD

**Issue by majk-p** [com-lihaoyi/os-lib#305]
Scala steward raised an os-lib update `0.10.6 -> 0.10.7` in https://github.com/siriusxm/snapshot4s/pull/45 but the build is failing. It looks like the last update introduced a change that breaks the [expecty](https://github.com/eed3si9n/expecty/) macro used by [weaver](https://github.com/disneystreaming/weaver-test).

Here's a minified reproduction example:
```scala
//> using dep "com.disneystreaming::weaver-cats:0.8.4"
//> using dep "com.lihaoyi::os-lib:0.10.7"

import weaver.*
import os.Path

object ExampleSuite extends FunSuite {

  test("os-lib test") {
    val path: os.Path = ???
    expect(
      path.startsWith(os.Path("/") / "tmp")
    )
  }

}
```
if you change the version in `"com.lihaoyi::os-lib:0.10.7"` to `0.10.6` it compiles. On the latest version it fails to compile with:

```
$ scala-cli compile .                                                                                                   
Compiling project (Scala 3.4.1, JVM (21))                                                                               
[error] ./test.scala:11:5                                                                                               
[error] Exception occurred while executing macro expansion.                                                             
[error] java.lang.RuntimeException: Expecty: Error rewriting expression.                                 
[error] Text:       path.startsWith(os.Path("/") / "tmp")                                                               
[error] AST : Apply(Select(Ident("path"), "startsWith"), List(Apply(Select(Apply(Apply(TypeApply(Select(Select(Ident("os
"), "Path"), "apply"), List(Inferred())), List(Literal(StringConstant("/")))), List(Ident("StringConvertible"))), "/"), 
List(Typed(Apply(Select(New(TypeIdent("RelPathChunk")), "<init>"), List(Apply(Ident("fromStringSegments"), List(Apply(Ap
ply(TypeApply(Select(Ident("Array"), "apply"), List(Inferred())), List(Typed(Repeated(List(Literal(StringConstant("tmp")
)), Inferred()), Inferred()))), List(Apply(TypeApply(Select(Ident("ClassTag"), "apply"), List(Inferred())), List(Literal
(ClassOfConstant(TypeRef(ThisType(TypeRef(NoPrefix(), "lang")), "String"))))))))))), TypeIdent("PathChunk"))))))
[error]         at com.eed3si9n.expecty.RecorderMacro.recordExpressions(RecorderMacro.scala:103)                        
[error]         at com.eed3si9n.expecty.RecorderMacro.inline$recordExpressions(RecorderMacro.scala:87)
[error]         at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$2$$anonfun$1(RecorderMacro.scala:36)           
[error]         at scala.collection.immutable.List.flatMap(List.scala:293)                          
[error]         at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$2(RecorderMacro.scala:36)           
[error]         at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$adapted$2(RecorderMacro.scala:38)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:109)     
[error]         at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1566)           
[error]         at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
[error]         at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock$$anonfun$1$$anonfun$1(tpd.scal
a:1259)                                                                                                                 
[error]         at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1241)                       [error]         at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1254)
[error]         at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock(tpd.scala:1259)               [error]         at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1546)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
[error]         at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:153)                          [error]         at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:89)
[error]         at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:3207)
[error]         at com.eed3si9n.expecty.RecorderMacro.apply(RecorderMacro.scala:38)                               
[error]         at com.eed3si9n.expecty.RecorderMacro$.apply(RecorderMacro.scala:245)                                   [error] Caused by: java.util.NoSuchElementException: None.get                   
[error]         at scala.None$.get(Option.scala:627)                                                                    
[error]         at scala.None$.get(Option.scala:626)                                                                   
```

Run the [gist](https://gist.github.com/majk-p/3943f16ab41019c24d7deaf61fcbd59f) to see full output
```
scala-cli test https://gist.github.com/majk-p/3943f16ab41019c24d7deaf61fcbd59f
```
Let me know if you feel like it's all good with os-lib and should be raised with weaver/expecty instead.

**Comment by Gedochao** [comment]
Ran into it in https://github.com/VirtusLab/scala-cli/pull/3173
A slightly minimised snippet of seemingly the same issue:
```scala
//> using dep com.eed3si9n.expecty::expecty:0.16.0
//> using dep com.lihaoyi::os-lib:0.10.7
import com.eed3si9n.expecty.Expecty.expect
@main def main = expect(Seq(os.pwd / "foo") == Seq(os.pwd / "bar"))
```
output:
```scala
-- Error: /Users/pchabelski/IdeaProjects/scala-cli-tests-2/untitled/os-lib-repro/oslibrepro.scala:5:23 
 5 |@main def main = expect(Seq(os.pwd / "foo") == Seq(os.pwd / "foo"))
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |Exception occurred while executing macro expansion.
   |java.lang.RuntimeException: Expecty: Error rewriting expression.
   |Text:                         Seq(os.pwd / "foo") == Seq(os.pwd / "foo")
   |AST : Apply(Select(Apply(TypeApply(Select(Ident("Seq"), "apply"), List(Inferred())), List(Typed(Repeated(List(Apply(Select(Select(Select(Ident("os"), "package"), "pwd"), "/"), List(Typed(Apply(Select(New(TypeIdent("RelPathChunk")), "<init>"), List(Apply(Ident("fromStringSegments"), List(Apply(Apply(TypeApply(Select(Ident("Array"), "apply"), List(Inferred())), List(Typed(Repeated(List(Literal(StringConstant("foo"))), Inferred()), Inferred()))), List(Apply(TypeApply(Select(Ident("ClassTag"), "apply"), List(Inferred())), List(Literal(ClassOfConstant(TypeRef(ThisType(TypeRef(NoPrefix(), "lang")), "String"))))))))))), TypeIdent("PathChunk"))))), Inferred()), Inferred()))), "=="), List(Apply(TypeApply(Select(Ident("Seq"), "apply"), List(Inferred())), List(Typed(Repeated(List(Apply(Select(Select(Select(Ident("os"), "package"), "pwd"), "/"), List(Typed(Apply(Select(New(TypeIdent("RelPathChunk")), "<init>"), List(Apply(Ident("fromStringSegments"), List(Apply(Apply(TypeApply(Select(Ident("Array"), "apply"), List(Inferred())), List(Typed(Repeated(List(Literal(StringConstant("foo"))), Inferred()), Inferred()))), List(Apply(TypeApply(Select(Ident("ClassTag"), "apply"), List(Inferred())), List(Literal(ClassOfConstant(TypeRef(ThisType(TypeRef(NoPrefix(), "lang")), "String"))))))))))), TypeIdent("PathChunk"))))), Inferred()), Inferred())))))
   |    at com.eed3si9n.expecty.RecorderMacro.recordExpressions(RecorderMacro.scala:103)
   |    at com.eed3si9n.expecty.RecorderMacro.inline$recordExpressions(RecorderMacro.scala:87)
   |    at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$2$$anonfun$1(RecorderMacro.scala:36)
   |    at scala.collection.immutable.List.flatMap(List.scala:294)
   |    at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$2(RecorderMacro.scala:36)
   |    at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$adapted$2(RecorderMacro.scala:38)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:109)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1571)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock$$anonfun$1$$anonfun$1(tpd.scala:1245)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1227)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1240)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock(tpd.scala:1245)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1551)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
   |    at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:153)
   |    at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:89)
   |    at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:3258)
   |    at com.eed3si9n.expecty.RecorderMacro.apply(RecorderMacro.scala:38)
   |    at com.eed3si9n.expecty.RecorderMacro$.varargs(RecorderMacro.scala:259)
   |Caused by: java.util.NoSuchElementException: None.get
   |    at scala.None$.get(Option.scala:627)
   |    at scala.None$.get(Option.scala:626)
   |    at com.eed3si9n.expecty.RecorderMacro.getAnchor(RecorderMacro.scala:238)
   |    at com.eed3si9n.expecty.RecorderMacro.getAnchor(RecorderMacro.scala:236)
   |    at com.eed3si9n.expecty.RecorderMacro.getAnchor(RecorderMacro.scala:235)
   |    at com.eed3si9n.expecty.RecorderMacro.recordValue(RecorderMacro.scala:220)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:133)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues$$anonfun$4(RecorderMacro.scala:163)
   |    at scala.collection.immutable.List.map(List.scala:247)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:163)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:133)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues$$anonfun$4(RecorderMacro.scala:163)
   |    at scala.collection.immutable.List.map(List.scala:247)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:163)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:133)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues$$anonfun$4(RecorderMacro.scala:163)
   |    at scala.collection.immutable.List.map(List.scala:247)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:163)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:173)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:133)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues$$anonfun$4(RecorderMacro.scala:163)
   |    at scala.collection.immutable.List.map(List.scala:247)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:163)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:133)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues$$anonfun$5(RecorderMacro.scala:174)
   |    at scala.collection.immutable.List.map(List.scala:247)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:174)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:129)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues$$anonfun$4(RecorderMacro.scala:163)
   |    at scala.collection.immutable.List.map(List.scala:247)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:163)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:133)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:171)
   |    at com.eed3si9n.expecty.RecorderMacro.recordSubValues(RecorderMacro.scala:163)
   |    at com.eed3si9n.expecty.RecorderMacro.recordAllValues(RecorderMacro.scala:133)
   |    at com.eed3si9n.expecty.RecorderMacro.recordExpression(RecorderMacro.scala:109)
   |    at com.eed3si9n.expecty.RecorderMacro.recordExpressions(RecorderMacro.scala:99)
   |    at com.eed3si9n.expecty.RecorderMacro.inline$recordExpressions(RecorderMacro.scala:87)
   |    at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$2$$anonfun$1(RecorderMacro.scala:36)
   |    at scala.collection.immutable.List.flatMap(List.scala:294)
   |    at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$2(RecorderMacro.scala:36)
   |    at com.eed3si9n.expecty.RecorderMacro.apply$$anonfun$adapted$2(RecorderMacro.scala:38)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:109)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1571)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock$$anonfun$1$$anonfun$1(tpd.scala:1245)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1227)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1240)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock(tpd.scala:1245)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1551)
   |    at dotty.tools.dotc.quoted.PickledQuotes$$anon$1.transform(PickledQuotes.scala:136)
   |    at dotty.tools.dotc.quoted.PickledQuotes$.spliceTerms(PickledQuotes.scala:153)
   |    at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:89)
   |    at scala.quoted.runtime.impl.QuotesImpl.unpickleExpr(QuotesImpl.scala:3258)
   |    at com.eed3si9n.expecty.RecorderMacro.apply(RecorderMacro.scala:38)
   |    at com.eed3si9n.expecty.RecorderMacro$.varargs(RecorderMacro.scala:259)
   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
   |    at dotty.tools.dotc.quoted.Interpreter.interpretedStaticMethodCall$$anonfun$1(Interpreter.scala:174)
   |    at dotty.tools.dotc.quoted.Interpreter.stopIfRuntimeException(Interpreter.scala:231)
   |    at dotty.tools.dotc.quoted.Interpreter.interpretedStaticMethodCall(Interpreter.scala:174)
   |    at dotty.tools.dotc.quoted.Interpreter.interpretTree(Interpreter.scala:80)
   |    at dotty.tools.dotc.transform.Splicer$SpliceInterpreter.interpretTree(Splicer.scala:266)
   |    at dotty.tools.dotc.quoted.Interpreter.interpretTree$$anonfun$2(Interpreter.scala:99)
   |    at dotty.tools.dotc.transform.Splicer$.$anonfun$2(Splicer.scala:61)
   |    at scala.Option.fold(Option.scala:263)
   |    at dotty.tools.dotc.transform.Splicer$.splice(Splicer.scala:61)
   |    at dotty.tools.dotc.inlines.Inliner.dotty$tools$dotc$inlines$Inliner$$expandMacro(Inliner.scala:1087)
   |    at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedSplice(Inliner.scala:838)
   |    at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3528)
   |    at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3567)
   |    at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:943)
   |    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3644)
   |    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3648)
   |    at dotty.tools.dotc.typer.ReTyper.typedTyped(ReTyper.scala:65)
   |    at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:3487)
   |    at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:3567)
   |    at dotty.tools.dotc.inlines.Inliner$InlineTyper.typedUnadapted(Inliner.scala:943)
   |    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3644)
   |    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3641)
   |    at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3648)
   |    at dotty.tools.dotc.inlines.Inliner.inlined(Inliner.scala:680)
   |    at dotty.tools.dotc.inlines.Inlines$InlineCall.expand(Inlines.scala:492)
   |    at dotty.tools.dotc.inlines.Inlines$.inlineCall(Inlines.scala:163)
   |    at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:100)
   |    at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:50)
   |    at dotty.tools.dotc.ast.TreeMapWithTrackedStats.transform(TreeMapWithTrackedStats.scala:63)
   |    at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transformMemberDef(Inlining.scala:141)
   |    at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:77)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1240)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1240)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1242)
   |    at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:58)
   |    at dotty.tools.dotc.ast.TreeMapWithTrackedStats.transform(TreeMapWithTrackedStats.scala:63)
   |    at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:101)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1605)
   |    at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
   |    at dotty.tools.dotc.ast.TreeMapWithTrackedStats.transform(TreeMapWithTrackedStats.scala:60)
   |    at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transformMemberDef(Inlining.scala:141)
   |    at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:77)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1240)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1240)
   |    at dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1242)
   |    at dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1616)
   |    at dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:67)
   |    at dotty.tools.dotc.ast.TreeMapWithTrackedStats.transform(TreeMapWithTrackedStats.scala:48)
   |    at dotty.tools.dotc.transform.Inlining$InliningTreeMap.transform(Inlining.scala:81)
   |    at dotty.tools.dotc.transform.Inlining$$anon$2.transform(Inlining.scala:63)
   |    at dotty.tools.dotc.transform.MacroTransform.run(MacroTransform.scala:20)
   |    at dotty.tools.dotc.transform.Inlining.run(Inlining.scala:39)
   |    at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:380)
   |    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
   |    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
   |    at scala.collection.immutable.List.foreach(List.scala:334)
   |    at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:373)
   |    at dotty.tools.dotc.transform.Inlining.runOn(Inlining.scala:43)
   |    at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:343)
   |    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
   |    at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
   |    at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
   |    at dotty.tools.dotc.Run.runPhases$1(Run.scala:336)
   |    at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:384)
   |    at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:396)
   |    at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
   |    at dotty.tools.dotc.Run.compileUnits(Run.scala:396)
   |    at dotty.tools.dotc.Run.compileSources(Run.scala:282)
   |    at dotty.tools.dotc.Run.compile(Run.scala:267)
   |    at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
   |    at dotty.tools.dotc.Driver.process(Driver.scala:201)
   |    at dotty.tools.dotc.Driver.process(Driver.scala:169)
   |    at dotty.tools.dotc.Driver.process(Driver.scala:181)
   |    at dotty.tools.dotc.Driver.main(Driver.scala:211)
   |    at dotty.tools.dotc.Main.main(Main.scala)
   |
   |----------------------------------------------------------------------------
   |Inline stack trace
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   |This location contains code that was inlined from Recorder.scala:32
    ----------------------------------------------------------------------------
1 error found
Compilation failed
```

**Comment by Gedochao** [comment]
It's a wild guess, but looking at the diff, the cause is likely to be https://github.com/com-lihaoyi/os-lib/pull/297, perhaps?

**Comment by Gedochao** [comment]
> Let me know if you feel like it's all good with os-lib and should be raised with weaver/expecty instead.

@majk-p [expecty](https://github.com/eed3si9n/expecty) hasn't had a new release since 2022, so either way we should probably track this here.

**Comment by majk-p** [comment]
> > Let me know if you feel like it's all good with os-lib and should be raised with weaver/expecty instead.
> 
> @majk-p [expecty](https://github.com/eed3si9n/expecty) hasn't had a new release since 2022, so either way we should probably track this here.

Agreed that sounds better, hence I reported here, just wanted to remain open for other perspective :wink:

**Comment by majk-p** [comment]
> It's a wild guess, but looking at the diff, the cause is likely to be #297, perhaps?

I thought so as well, on my fork I've reverted the change (see https://github.com/com-lihaoyi/os-lib/pull/306) and the issue seems resolved on locally published version:

```
$ scala-cli compile .
Compiling project (Scala 3.4.1, JVM (21))
Compiled project (Scala 3.4.1, JVM (21))
[hint] ./test.scala:2:16
[hint] "os-lib is outdated, update to 0.10.7"
[hint]      os-lib 0.0.0-414-05f6f8-DIRTY28e2c72d -> com.lihaoyi::os-lib:0.10.7
[hint] //> using dep "com.lihaoyi::os-lib:0.0.0-414-05f6f8-DIRTY28e2c72d"
[hint]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@lihaoyi @pawelsadlo WDYT about reverting https://github.com/com-lihaoyi/os-lib/pull/297 from main until this gets fixed?

**Comment by lihaoyi** [comment]
Can you guys stay on 0.10.6 for a while instead? There's no requirement for you to upgrade immediately, just open an issue with a repro and we can take our time to investigate and resolve it
